### ISSUE TITLE
Usage for the new TextParser

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#110]
Hey @ndaelman-hu @ladinesa , do you have any examples on how to use the new TextParser?

From the branch cmb2_parser, I understood there is a much easier way of writing regexes into the archive directly, but I think Nathan told me this is not updated with the latest changes in the TextParser.

I am trying to write some regexes and wanted to know the status of this. But also, let me know if I misunderstood something on this topic.

**Comment by ndaelman-hu** [comment]
Nothing changed to the regexes. That'd be silly, since they're quite standardized and complete. Rather, this new version supports a new form of section/quantity composition that sidesteps the way we usually map to the archive in the current parsers. Could be appropriate for new parsers, that's what I was testing. Once I'm through with these feature requests, this will come back on my priority list.

**Comment by JosePizarro3** [comment]
Hi, I know the regexes didn't change, but rather the way of writing them to archive quantities and sections (check out my message again).

For me it is enough to have a copy-paste example lines so I can check it on my own (and which is better than reading the class itself).

I cannot wait months for it, as I am writing parsers right now and better have this for the let go than going with the old style.

**Comment by ndaelman-hu** [comment]
The example is on the cmb2 branch. Its applicability depends on the case.

**Comment by JosePizarro3** [comment]
Ah, so is that updated? I recall you told me not with the merged changes.

I will take a look then.
